### ISSUE TITLE
TORCS installation

### ISSUE THREAD

**Issue by VictorySpecificationII** [madras-simulator/MADRaS#29]
Will the TORCS 1.3.7 SCR patched simulator work? That's what I have at the moment

**Comment by rudrasohan** [comment]
Hi, other version of torcs won't work as to facilitate multi agent support /parallelized training we have incorporated some additional changes, hence I would suggest to use the one [here](https://github.com/madras-simulator/TORCS). In case some other things are dependent on that particular version of TORCS then I would suggest to use the Version1 branch of the MADRaS repo but otherwise I would strongly recommend to use the above version of TORCS as Version 1 lacks some features and is more unstable than the master.

**Comment by VictorySpecificationII** [comment]
Thank you.

For reference, I'm running on Ubuntu 18.04.

I've been trying to install TORCS 1.3.6, using ./configure and a custom path as a prefix with no luck. I've tried a number of approaches to installing it alongside 1.3.7 as I have some developed material in that version. Any ideas as to how to install it alongside? I have downloaded the environment-modules package in order to allow me to switch from version to version.

Any help would be much appreciated.

Thank you
